
export PATH=$PATH:$MCRIBS_HOME/bin

#$MCRIBS_HOME/MIRTK/MIRTK-install/bin:$MCRIBS_HOME/MIRTK/MIRTK-install/lib/tools
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MCRIBS_HOME/MIRTK/MIRTK-install/lib:$MCRIBS_HOME/VTK/VTK-install/lib
#export PYTHONPATH=$PYTHONPATH:$MCRIBS_HOME/MIRTK/MIRTK-install/lib/python:$MCRIBS_HOME/lib/python
